# Generated by Django 2.2 on 2021-09-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/postimages'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='longdesc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='shortdesc',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
